var tooltipMap = {
		"fillTimesheetTT": ["Fill and <b>save</b> timesheet daily and <b>submit</b> on every Friday without fail.",
		                    "Input effort HH format", 
		                    "Minimum Effort: 0.5 denotes 30 minutes.If effort is less than 30 minutes,can club with other task and mention in comment box.Fill 0 in case of no effort",
		                    "Maximum Effort: 24H.",
		                    "Total week effort must be greater or equals 45 Hours.",
		                    "Input effort value must be multiple of 0.5",
		                    "<b>Apply leave before filling Leave Task.</b>"],
        "quickLinksTT": ["Customize quick links based on daily use.", 
		 		         "Enable quick link by clicking on settings icon next to profile picture."],
	    "announancementTT": ["Display latest announcement by HR/Admin/Finanace etc.", 
 				 	         "Click on link to view corresponding announcement details."],
       "timesheetProjectListTT": ["List of active assigned project to logged in user.", 
 				 	              "On select project, all active task populate in task list."],
       "generateEmpDocTT": ["User group populate based on selected policy group.", 
				 	        "List of documents based on selected user group.",
				 	        "List of templates based on selected document type.",
				 	        "Provide username if available or leave it blank.",
				 	       "First/Last Name and personal Email-Id of intended person is required for document generation.",
				 	       "Note down document reference number for future reference."],
      "manageAnnoncementTT": ["All active announcement display on dashboard.", 
 				 	          "Type of announcement:PDF,Webpage,Popup",
 				 	          "<b>PDF</b>:Upload respective pdf and same is visible to user on dashboard when click on corresponsing link.",
 				 	          "<b>Webpage</b>:View new webpage with complete description when click on corresponsing link on dashboard.",
 				 	          "<b>Popup</b>:New pop up will open when user clicks on link",
 				 	          "Enable/disable announcement by toggle button.",
 				 	          "Provide meaningful and consize title.Same is visible on dashboard."],				 	      
			"fillMOAFTT": ["Missed Out Attendance Form(MOAF) captures missed attendance under given category.", 
		                  "Select date for which attendance is not captured.",
		                  "Select InTime or OutTime or Both respectively.",
		                  "MOAF is subjected to HR/Admin approval.",
		                  "User should have valid proof/reason in case of any discrepancy",
		                  "Provide appropriate reason for missing attendance."],
		"emailNotificationTT": ["All modules have various event for mail trigger.", 
								"Event name are derived based on it's functionality",
								"Activate/Deactivate mail trigger through switch button."],
		"manageUserAccessTT": ["Active access groups are listed in dropdown", 
							   "On selecting access group,corresponding access on all function is shown.",
							   "User may allow/remove access for every function for selected access group.",
		                       "Changes will affect only after relogin if users in selected group are logged in."],
		"manageUserGroupTT": ["Create new group by providing logical name to provide access of various function in application.", 
		                      "All existing group are listed in alphabatical order.",
		                      "User may add/remove users from group by clicking on <b>Modify Group Users</b> button.",
		                      "User may edit group name.",
		                      "Before deletion of any group, It is mandetory to remove all users from group first."],				  
		"employeeDirectoryTT": ["List of active user's primary contact information.", 
								"User list are based on Policy Group of logged in user.",
								"Wildcard serch box provided for searching users."],
		   "viewAttendanceTT": ["Default view display current month attendance of logged in user.", 
								"View past attendance data by providing Start/End date.",
								"<b>Status:</b>Present,Absent,On Leave,Holiday and Week Off.",
								"Connect with HR/Admin in case of any discrepency in status.",
								"In case user finds In/Out time is/are not accurate,Fill MOAF with valid reason.",
								"Deficient/Extra working hour is calculated based on <b>9.00 hours/day.</b>"],
"approveEmployeesAttendanceTT": ["Pending MOAFs list.", 
						         "HR/Admin may take corresponding action.",
								 "In case of discrepency Manager approval would be required."],
 "employeesAttendanceReportTT": ["Select date range.", 
						         "To get attendance report for users in selected project,<br>do not select user from dropdown",
						         "User may download corresponding generated data in XLS format."],
        "approveRejectTSTT": ["Default list shows pending timesheet for past three months including current month under logged in user.", 
                              "User may drill down Timesheet based on given filters such as Status,Employee Name,Date range and result per page.",
							  "Total effort/week is shown and User may view effort distribution among tasks by clicking on <b>View</b> button.",
							  "User may approve multiple timesheet by selecting checkbox and click on <b>Approve Selected</>",
							  "It is advisable to add remark inside View Popup whenever Reject action is taken against timesheet."],
  "monthlyTimesheetReportTT": ["Time effort estimation of user in selected Project for given month.", 
                               "Generate and download xls file.",
                               "Username dropdown populates users who are reporting to logged in user.",
                               "Users deployed on client location are requested to send monthly timesheet report <b>approved by client to HR</b> on or before 26th of every month."],
  "weeklyTSStatusReportTT": ["Weekly status report for individual as well as all user in respective policy group.", 
                             "HR user able to track timesheet status of all users between given date range."],
		"createTemplateTT": ["Create generic template for each group.", 
		                     "Create as many template based on User Group.",
		                     "Define unique and logical template name."],
	  "timesheetTaskListTT":["In case task is not present,ask RM to add task under corresponding project."],
	  "showActionHistoryTSTT":["View all action taken on selected week timesheet."],
	  "showPastTSHistoryTT":["View past Timesheet History on Month basis.",
	                           "Filter past data by Year and Month."],
	  "applyLeaveForOtherTT22":["Manager/HR may apply leave on behalf of listed user.",
	                            "Each leave type has authorization constraint for Manager and HR."],
      "ownLeaveRequestListTT23":["Default view display pending leave request of logged in user.",
                                "User may view his/her past request list based on status."],
"leaveRequestListUnderUserTT24":["Default view display pending leave request under logged in user.",
                                 "Approver may initiate Meeting request/Mail Intimation for corresponding leave request.",
                                 "It is advised to provide remark before leave approve/reject action.",
                                 "Approver may check other users if they are on leave on same day/days."],
"manageLeaveTypeTT25":["Authorized user may create/view/modify/delete leave types.",
                       "<b>New Leave Name:</b> Abbreviated leave name visible to user.",
                       "<b>Leave Description:</b> Detailed leave name.",
                       "<b>Policy Group:</b> Applicable policy group.",
                       "<b>Leave Group:</b> Leave balance is mandatory in case paid leave.For unpaid leave balance updation not required.",
                       "<b>Cumulative Group:</b> Same cumulative group share leave balance.",
                       "<b>Max day per request:</b> Default value is 999 or define any positive number to restrict user for max days in each request.",
                       "<b>Apply min day before:</b> Default value is 0 or define any positive number to restrict user to apply leave before min specified days.",
                       "<b>Apply on behalf:</b> Only checked user may apply this leave type for users under him/her.",
                       "User may active/inactive leave at any time and edit above configuration for leave."],
   "leaveBalanceUpdateTT26":["Authorized user may update all users leave balance under his/her policy group.",
                             "User may update balance of individual or uplaod updated balance xls sheet as given in template.",
                             "Make sure uploaded sheet name is <b>LeaveBalanceExcel.xlsx</b>.",
                             "<b>Important!</b> Do not edit header and username.Only update balance and add row if required."],
    "generateLeaveReportTT27":["Authorized user may generate leave report based on given parameter.",
                               "User may create report for individual or all users under selected policy group for given date range."],
   "empWeeklyAttnReportTT28":["Default view weekly total punched hours of current month of logged in user.",
                              "User may select date range and user to view weekly report.",
                              "Week starts on <b>Sunday</b> and ends on <b>Saturday</b>.",
                              "User may download report in XLS format."],
  "empPastRMSListTT29":["User may withdraw request any time before approval from Finance team.",
                        "User may save request in his/her draft and submit later by opending RMS form by click on enabled link Request Number.",
                        "On successfull request submition, reporting manager get notified via mail.",
                        "Please perform any action on expense request carefully."],
  "viewPayslipTT32":["Select Year and Month to view payslip.",
					 "User may view his/her payslip since joining date to last generated month."]};









