/*
 * Java bean class for entity "ses_m11_emp_element" 
 * Created on 2018-04-17 ( Date ISO 2018-04-17 - Time 15:56:08 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.supraits.viewBean.payroll;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for entity "ses_m11_emp_element"
 * 
 * @author Telosys Tools Generator
 *
 */
public class SesM11EmpElement implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    empElementId ; // Id or Primary Key

    private Integer    employeeId   ;
    private Integer    elementId    ;
    private String     verifiedFlag ;
    private String     processedFlag ;
    private String     formulaAlias ;
    private String     payFrequency ;
    private String     billVarification ;
    private String     taxExemted   ;
    private String     formulaFlag  ;
    private String     formulaType  ;
    private String     formulaText  ;
    private Integer    maxLimit     ;
    private Date       nextEligibleDate ;
    private Date       startDate    ;
    private Date       endDate      ;
    private Integer    payValue     ;
    private String     elementType  ;
    private String     displayFlag  ;
    private Integer    entityId     ;
    private Integer    clientId     ;
    private Date       lastUpdatedBy ;
    private Date       lastUpdateDate ;
    private String     createdBy    ;
    private Date       creationDate ;
    private Integer    lastUpdateSessionId ;

    /**
     * Default constructor
     */
    public SesM11EmpElement() {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR ID OR PRIMARY KEY 
    //----------------------------------------------------------------------
    
    
    
    /**
     * Set the "empElementId" field value
     * This field is mapped on the database column "EMP_ELEMENT_ID" ( type "INT", NotNull : true ) 
     * @param empElementId
     */
	public void setEmpElementId( Integer empElementId ) {
        this.empElementId = empElementId ;
    }
    public String getElementType() {
		return elementType;
	}

	public void setElementType(String elementType) {
		this.elementType = elementType;
	}

	public String getDisplayFlag() {
		return displayFlag;
	}

	public void setDisplayFlag(String displayFlag) {
		this.displayFlag = displayFlag;
	}

	/**
     * Get the "empElementId" field value
     * This field is mapped on the database column "EMP_ELEMENT_ID" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getEmpElementId() {
        return this.empElementId;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS
    //----------------------------------------------------------------------
    /**
     * Set the "employeeId" field value
     * This field is mapped on the database column "EMPLOYEE_ID" ( type "INT", NotNull : false ) 
     * @param employeeId
     */
    public void setEmployeeId( Integer employeeId ) {
        this.employeeId = employeeId;
    }
    /**
     * Get the "employeeId" field value
     * This field is mapped on the database column "EMPLOYEE_ID" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getEmployeeId() {
        return this.employeeId;
    }

    /**
     * Set the "elementId" field value
     * This field is mapped on the database column "ELEMENT_ID" ( type "INT", NotNull : false ) 
     * @param elementId
     */
    public void setElementId( Integer elementId ) {
        this.elementId = elementId;
    }
    /**
     * Get the "elementId" field value
     * This field is mapped on the database column "ELEMENT_ID" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getElementId() {
        return this.elementId;
    }

    /**
     * Set the "verifiedFlag" field value
     * This field is mapped on the database column "VERIFIED_FLAG" ( type "VARCHAR", NotNull : false ) 
     * @param verifiedFlag
     */
    public void setVerifiedFlag( String verifiedFlag ) {
        this.verifiedFlag = verifiedFlag;
    }
    /**
     * Get the "verifiedFlag" field value
     * This field is mapped on the database column "VERIFIED_FLAG" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getVerifiedFlag() {
        return this.verifiedFlag;
    }

    /**
     * Set the "processedFlag" field value
     * This field is mapped on the database column "PROCESSED_FLAG" ( type "VARCHAR", NotNull : false ) 
     * @param processedFlag
     */
    public void setProcessedFlag( String processedFlag ) {
        this.processedFlag = processedFlag;
    }
    /**
     * Get the "processedFlag" field value
     * This field is mapped on the database column "PROCESSED_FLAG" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getProcessedFlag() {
        return this.processedFlag;
    }

    /**
     * Set the "formulaAlias" field value
     * This field is mapped on the database column "FORMULA_ALIAS" ( type "VARCHAR", NotNull : false ) 
     * @param formulaAlias
     */
    public void setFormulaAlias( String formulaAlias ) {
        this.formulaAlias = formulaAlias;
    }
    /**
     * Get the "formulaAlias" field value
     * This field is mapped on the database column "FORMULA_ALIAS" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getFormulaAlias() {
        return this.formulaAlias;
    }

    /**
     * Set the "payFrequency" field value
     * This field is mapped on the database column "PAY_FREQUENCY" ( type "VARCHAR", NotNull : false ) 
     * @param payFrequency
     */
    public void setPayFrequency( String payFrequency ) {
        this.payFrequency = payFrequency;
    }
    /**
     * Get the "payFrequency" field value
     * This field is mapped on the database column "PAY_FREQUENCY" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getPayFrequency() {
        return this.payFrequency;
    }

    /**
     * Set the "billVarification" field value
     * This field is mapped on the database column "BILL_VARIFICATION" ( type "VARCHAR", NotNull : false ) 
     * @param billVarification
     */
    public void setBillVarification( String billVarification ) {
        this.billVarification = billVarification;
    }
    /**
     * Get the "billVarification" field value
     * This field is mapped on the database column "BILL_VARIFICATION" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getBillVarification() {
        return this.billVarification;
    }

    /**
     * Set the "taxExemted" field value
     * This field is mapped on the database column "TAX_EXEMTED" ( type "VARCHAR", NotNull : false ) 
     * @param taxExemted
     */
    public void setTaxExemted( String taxExemted ) {
        this.taxExemted = taxExemted;
    }
    /**
     * Get the "taxExemted" field value
     * This field is mapped on the database column "TAX_EXEMTED" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getTaxExemted() {
        return this.taxExemted;
    }

    /**
     * Set the "formulaFlag" field value
     * This field is mapped on the database column "FORMULA_FLAG" ( type "VARCHAR", NotNull : false ) 
     * @param formulaFlag
     */
    public void setFormulaFlag( String formulaFlag ) {
        this.formulaFlag = formulaFlag;
    }
    /**
     * Get the "formulaFlag" field value
     * This field is mapped on the database column "FORMULA_FLAG" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getFormulaFlag() {
        return this.formulaFlag;
    }

    /**
     * Set the "formulaType" field value
     * This field is mapped on the database column "FORMULA_TYPE" ( type "VARCHAR", NotNull : false ) 
     * @param formulaType
     */
    public void setFormulaType( String formulaType ) {
        this.formulaType = formulaType;
    }
    /**
     * Get the "formulaType" field value
     * This field is mapped on the database column "FORMULA_TYPE" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getFormulaType() {
        return this.formulaType;
    }

    /**
     * Set the "formulaText" field value
     * This field is mapped on the database column "FORMULA_TEXT" ( type "VARCHAR", NotNull : false ) 
     * @param formulaText
     */
    public void setFormulaText( String formulaText ) {
        this.formulaText = formulaText;
    }
    /**
     * Get the "formulaText" field value
     * This field is mapped on the database column "FORMULA_TEXT" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getFormulaText() {
        return this.formulaText;
    }

    /**
     * Set the "maxLimit" field value
     * This field is mapped on the database column "MAX_LIMIT" ( type "INT", NotNull : false ) 
     * @param maxLimit
     */
    public void setMaxLimit( Integer maxLimit ) {
        this.maxLimit = maxLimit;
    }
    /**
     * Get the "maxLimit" field value
     * This field is mapped on the database column "MAX_LIMIT" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getMaxLimit() {
        return this.maxLimit;
    }

    /**
     * Set the "nextEligibleDate" field value
     * This field is mapped on the database column "NEXT_ELIGIBLE_DATE" ( type "DATE", NotNull : false ) 
     * @param nextEligibleDate
     */
    public void setNextEligibleDate( Date nextEligibleDate ) {
        this.nextEligibleDate = nextEligibleDate;
    }
    /**
     * Get the "nextEligibleDate" field value
     * This field is mapped on the database column "NEXT_ELIGIBLE_DATE" ( type "DATE", NotNull : false ) 
     * @return the field value
     */
    public Date getNextEligibleDate() {
        return this.nextEligibleDate;
    }

    /**
     * Set the "startDate" field value
     * This field is mapped on the database column "START_DATE" ( type "DATE", NotNull : false ) 
     * @param startDate
     */
    public void setStartDate( Date startDate ) {
        this.startDate = startDate;
    }
    /**
     * Get the "startDate" field value
     * This field is mapped on the database column "START_DATE" ( type "DATE", NotNull : false ) 
     * @return the field value
     */
    public Date getStartDate() {
        return this.startDate;
    }

    /**
     * Set the "endDate" field value
     * This field is mapped on the database column "END_DATE" ( type "DATE", NotNull : false ) 
     * @param endDate
     */
    public void setEndDate( Date endDate ) {
        this.endDate = endDate;
    }
    /**
     * Get the "endDate" field value
     * This field is mapped on the database column "END_DATE" ( type "DATE", NotNull : false ) 
     * @return the field value
     */
    public Date getEndDate() {
        return this.endDate;
    }

    /**
     * Set the "payValue" field value
     * This field is mapped on the database column "PAY_VALUE" ( type "INT", NotNull : false ) 
     * @param payValue
     */
    public void setPayValue( Integer payValue ) {
        this.payValue = payValue;
    }
    /**
     * Get the "payValue" field value
     * This field is mapped on the database column "PAY_VALUE" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getPayValue() {
        return this.payValue;
    }

    /**
     * Set the "entityId" field value
     * This field is mapped on the database column "ENTITY_ID" ( type "INT", NotNull : false ) 
     * @param entityId
     */
    public void setEntityId( Integer entityId ) {
        this.entityId = entityId;
    }
    /**
     * Get the "entityId" field value
     * This field is mapped on the database column "ENTITY_ID" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getEntityId() {
        return this.entityId;
    }

    /**
     * Set the "clientId" field value
     * This field is mapped on the database column "CLIENT_ID" ( type "INT", NotNull : false ) 
     * @param clientId
     */
    public void setClientId( Integer clientId ) {
        this.clientId = clientId;
    }
    /**
     * Get the "clientId" field value
     * This field is mapped on the database column "CLIENT_ID" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getClientId() {
        return this.clientId;
    }

    /**
     * Set the "lastUpdatedBy" field value
     * This field is mapped on the database column "LAST_UPDATED_BY" ( type "DATE", NotNull : false ) 
     * @param lastUpdatedBy
     */
    public void setLastUpdatedBy( Date lastUpdatedBy ) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    /**
     * Get the "lastUpdatedBy" field value
     * This field is mapped on the database column "LAST_UPDATED_BY" ( type "DATE", NotNull : false ) 
     * @return the field value
     */
    public Date getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }

    /**
     * Set the "lastUpdateDate" field value
     * This field is mapped on the database column "LAST_UPDATE_DATE" ( type "DATE", NotNull : false ) 
     * @param lastUpdateDate
     */
    public void setLastUpdateDate( Date lastUpdateDate ) {
        this.lastUpdateDate = lastUpdateDate;
    }
    /**
     * Get the "lastUpdateDate" field value
     * This field is mapped on the database column "LAST_UPDATE_DATE" ( type "DATE", NotNull : false ) 
     * @return the field value
     */
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }

    /**
     * Set the "createdBy" field value
     * This field is mapped on the database column "CREATED_BY" ( type "VARCHAR", NotNull : false ) 
     * @param createdBy
     */
    public void setCreatedBy( String createdBy ) {
        this.createdBy = createdBy;
    }
    /**
     * Get the "createdBy" field value
     * This field is mapped on the database column "CREATED_BY" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Set the "creationDate" field value
     * This field is mapped on the database column "CREATION_DATE" ( type "DATE", NotNull : false ) 
     * @param creationDate
     */
    public void setCreationDate( Date creationDate ) {
        this.creationDate = creationDate;
    }
    /**
     * Get the "creationDate" field value
     * This field is mapped on the database column "CREATION_DATE" ( type "DATE", NotNull : false ) 
     * @return the field value
     */
    public Date getCreationDate() {
        return this.creationDate;
    }

    /**
     * Set the "lastUpdateSessionId" field value
     * This field is mapped on the database column "LAST_UPDATE_SESSION_ID" ( type "INT", NotNull : false ) 
     * @param lastUpdateSessionId
     */
    public void setLastUpdateSessionId( Integer lastUpdateSessionId ) {
        this.lastUpdateSessionId = lastUpdateSessionId;
    }
    /**
     * Get the "lastUpdateSessionId" field value
     * This field is mapped on the database column "LAST_UPDATE_SESSION_ID" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getLastUpdateSessionId() {
        return this.lastUpdateSessionId;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(empElementId);
        sb.append("|");
        sb.append(employeeId);
        sb.append("|");
        sb.append(elementId);
        sb.append("|");
        sb.append(verifiedFlag);
        sb.append("|");
        sb.append(processedFlag);
        sb.append("|");
        sb.append(formulaAlias);
        sb.append("|");
        sb.append(payFrequency);
        sb.append("|");
        sb.append(billVarification);
        sb.append("|");
        sb.append(taxExemted);
        sb.append("|");
        sb.append(formulaFlag);
        sb.append("|");
        sb.append(formulaType);
        sb.append("|");
        sb.append(formulaText);
        sb.append("|");
        sb.append(maxLimit);
        sb.append("|");
        sb.append(nextEligibleDate);
        sb.append("|");
        sb.append(startDate);
        sb.append("|");
        sb.append(endDate);
        sb.append("|");
        sb.append(payValue);
        sb.append("|");
        sb.append(entityId);
        sb.append("|");
        sb.append(clientId);
        sb.append("|");
        sb.append(lastUpdatedBy);
        sb.append("|");
        sb.append(lastUpdateDate);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(creationDate);
        sb.append("|");
        sb.append(lastUpdateSessionId);
        return sb.toString(); 
    } 

}
