package com.supraits.viewBean.payroll;
/*
 * Java bean class for entity "ses_m11_element_group" 
 * Created on 2018-04-17 ( Date ISO 2018-04-17 - Time 15:56:08 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

import java.io.Serializable;

import java.util.Date;
import java.util.List;

import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotEmpty;

/**
 * Java bean for entity "ses_m11_element_group"
 * 
 * @author Telosys Tools Generator
 *
 */
public class SesM11ElementGroup implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    elementGroupId ; // Id or Primary Key

    private String elementGroupName;
    
    private String status;
    
    private Integer entityId;
	
    private Integer clientId;
	
    private String lastUpdatedBy;
    
    private Date lastUpdateDate;
    
    private String createdBy;
    
    private Date creationDate;
    
    private Integer lastUpdateSessionId ;
	
	private List<SesM11Element> sesM11ElementList;

    /**
     * Default constructor
     */
    public SesM11ElementGroup() {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR ID OR PRIMARY KEY 
    //----------------------------------------------------------------------
    
    
    
    
    /**
     * Set the "elementGroupId" field value
     * This field is mapped on the database column "ELEMENT_GROUP_ID" ( type "INT", NotNull : true ) 
     * @param elementGroupId
     */
	public void setElementGroupId( Integer elementGroupId ) {
        this.elementGroupId = elementGroupId ;
    }
    public List<SesM11Element> getSesM11ElementList() {
		return sesM11ElementList;
	}

	public void setSesM11ElementList(List<SesM11Element> sesM11ElementList) {
		this.sesM11ElementList = sesM11ElementList;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	/**
     * Get the "elementGroupId" field value
     * This field is mapped on the database column "ELEMENT_GROUP_ID" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getElementGroupId() {
        return this.elementGroupId;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS
    //----------------------------------------------------------------------
    /**
     * Set the "elementId" field value
     * This field is mapped on the database column "ELEMENT_ID" ( type "INT", NotNull : false ) 
     * @param elementId
     */
    public void setElementGroupName( String elementGroupName ) {
        this.elementGroupName = elementGroupName;
    }
    /**
     * Get the "elementId" field value
     * This field is mapped on the database column "ELEMENT_ID" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public String getStatus() {
        return this.status;
    }
    /**
     * Set the "status" field value
     * This field is mapped on the database column "STATUS" ( type "String", NotNull : false ) 
     * @param elementId
     */
    public void setStatus( String status ) {
        this.status = status;
    }
    /**
     * Get the "elementId" field value
     * This field is mapped on the database column "ELEMENT_ID" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public String getElementGroupName() {
        return this.elementGroupName;
    }
    

    /**
     * Set the "entityId" field value
     * This field is mapped on the database column "ENTITY_ID" ( type "INT", NotNull : false ) 
     * @param entityId
     */
    public void setEntityId( Integer entityId ) {
        this.entityId = entityId;
    }
    /**
     * Get the "entityId" field value
     * This field is mapped on the database column "ENTITY_ID" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getEntityId() {
        return this.entityId;
    }

    /**
     * Set the "clientId" field value
     * This field is mapped on the database column "CLIENT_ID" ( type "INT", NotNull : false ) 
     * @param clientId
     */
    public void setClientId( Integer clientId ) {
        this.clientId = clientId;
    }
    /**
     * Get the "clientId" field value
     * This field is mapped on the database column "CLIENT_ID" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getClientId() {
        return this.clientId;
    }

    /**
     * Set the "lastUpdatedBy" field value
     * This field is mapped on the database column "LAST_UPDATED_BY" ( type "DATE", NotNull : false ) 
     * @param lastUpdatedBy
     */
    public void setLastUpdatedBy( String lastUpdatedBy ) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    /**
     * Get the "lastUpdatedBy" field value
     * This field is mapped on the database column "LAST_UPDATED_BY" ( type "DATE", NotNull : false ) 
     * @return the field value
     */
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }

    /**
     * Set the "lastUpdateDate" field value
     * This field is mapped on the database column "LAST_UPDATE_DATE" ( type "DATE", NotNull : false ) 
     * @param lastUpdateDate
     */
    public void setLastUpdateDate( Date lastUpdateDate ) {
        this.lastUpdateDate = lastUpdateDate;
    }
    /**
     * Get the "lastUpdateDate" field value
     * This field is mapped on the database column "LAST_UPDATE_DATE" ( type "DATE", NotNull : false ) 
     * @return the field value
     */
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }

    /**
     * Set the "createdBy" field value
     * This field is mapped on the database column "CREATED_BY" ( type "VARCHAR", NotNull : false ) 
     * @param createdBy
     */
    public void setCreatedBy( String createdBy ) {
        this.createdBy = createdBy;
    }
    /**
     * Get the "createdBy" field value
     * This field is mapped on the database column "CREATED_BY" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Set the "creationDate" field value
     * This field is mapped on the database column "CREATION_DATE" ( type "DATE", NotNull : false ) 
     * @param creationDate
     */
    public void setCreationDate( Date creationDate ) {
        this.creationDate = creationDate;
    }
    /**
     * Get the "creationDate" field value
     * This field is mapped on the database column "CREATION_DATE" ( type "DATE", NotNull : false ) 
     * @return the field value
     */
    public Date getCreationDate() {
        return this.creationDate;
    }

    /**
     * Set the "lastUpdateSessionId" field value
     * This field is mapped on the database column "LAST_UPDATE_SESSION_ID" ( type "INT", NotNull : false ) 
     * @param lastUpdateSessionId
     */
    public void setLastUpdateSessionId( Integer lastUpdateSessionId ) {
        this.lastUpdateSessionId = lastUpdateSessionId;
    }
    /**
     * Get the "lastUpdateSessionId" field value
     * This field is mapped on the database column "LAST_UPDATE_SESSION_ID" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getLastUpdateSessionId() {
        return this.lastUpdateSessionId;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(elementGroupId);
        sb.append("|");
        sb.append(elementGroupName);
        sb.append("|");
        sb.append("|");
        sb.append(entityId);
        sb.append("|");
        sb.append(clientId);
        sb.append("|");
        sb.append(lastUpdatedBy);
        sb.append("|");
        sb.append(lastUpdateDate);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(creationDate);
        sb.append("|");
        sb.append(lastUpdateSessionId);
        sb.append("|");
        sb.append(sesM11ElementList.toString());
        return sb.toString(); 
    } 

}

